### ISSUE TITLE
Some links with descriptions don't work well

### ISSUE THREAD

**Issue by Ypot** [yantar92/org#11]
**Describe the bug**
Not sure why, but an exisiting buffer link description doesn't work as expected

![1](https://user-images.githubusercontent.com/30699014/103280860-b3e42d00-49d1-11eb-9cb5-956e3ac882da.JPG)

**Expected behavior**

![2](https://user-images.githubusercontent.com/30699014/103280981-fd347c80-49d1-11eb-9f3c-512e594f8c87.JPG)

**To Reproduce**
`** PROYECTO _19043-EA_- TSA e ILP [92/98] [[file:z:/OFICINA TECNICA/\[PEDIDOS\]/2019/19-043-EA (MAQUINA ANODIZADO)/][PEDIDO]]  [[file:z://OFICINA TECNICA/PLANOS/EA/19-043-EA-(MAQUINA ANODIZADO)][PLANOS]]`

**Comment by yantar92** [comment]
Cannot reproduce. Did you try without your personal config? (https://github.com/yantar92/org#testing-the-branch)
![screenshort](https://user-images.githubusercontent.com/10819266/103282278-3986cd80-4a10-11eb-9498-1ca060f1a3c6.png)

**Comment by Ypot** [comment]
Thanks. I don't know how to try your "org" without my personal config (no command line staff one here), but I suppose it should work just like in your system.

If I can help you with something let me know (sharing personal config, etc.)

Best regards.

EDIT: Wait: I will comment all my .init file but your lines
EDIT 2: It works fine. My personal configuration seems to have some issue with your code.

**Comment by yantar92** [comment]
> My personal configuration seems to have some issue with your code.

You can try bug-hunter package to identify the place in your config that is causing trouble. (https://github.com/Malabarba/elisp-bug-hunter)

**Comment by Ypot** [comment]
Nice package!!

These lines were the culprit:

```
;; How to make part of a word bold in org-mode
;; https://code-examples.net/en/q/1296be

(setcar org-emphasis-regexp-components " \t('\"{[:alpha:]")
(setcar (nthcdr 1 org-emphasis-regexp-components) "[:alpha:]- \t.,:!?;'\")}\\")
(org-set-emph-re 'org-emphasis-regexp-components org-emphasis-regexp-components)
```

**Comment by yantar92** [comment]
> These lines were the culprit:

Trying just these lines still show normal behavior on my side. Apparently, the lines you provided also interact with some earlier code in your init file. You may need to move these lines at the top of your init file (after `(require 'org)`) and repeat the bug hunting.

**Comment by Ypot** [comment]
All right. New culprit, related aswell to emphasis:

```
  Caused by the following expression:
    (setq org-hide-emphasis-markers t)
```

**Comment by yantar92** [comment]
I confirm the problem. It is not very easy to fix. Let me see what I can do.

**Comment by yantar92** [comment]
Should be fixed now.

**Comment by Ypot** [comment]
Fixation confirmed
