### ISSUE TITLE
Possible incompatibility with org-noter

### ISSUE THREAD

**Issue by Ypot** [yantar92/org#12]
**Describe the bug**
[org-noter](https://github.com/weirdNox/org-noter) frame doesn't unfold the heading.

![Children](https://user-images.githubusercontent.com/30699014/103414299-b2effe80-4b7d-11eb-8834-b6f7f0d02426.JPG)

![subtree](https://user-images.githubusercontent.com/30699014/103414302-b5eaef00-4b7d-11eb-84c7-37ab7ce6f9c8.JPG)

![showall](https://user-images.githubusercontent.com/30699014/103414306-b8e5df80-4b7d-11eb-9c89-935117bdcf2e.JPG)

**Expected behavior**

![Children-2](https://user-images.githubusercontent.com/30699014/103414347-ddda5280-4b7d-11eb-8107-7cb918d25a3a.JPG)

**To Reproduce**
Open org-noter frame and try to unfold the heading

**Comment by yantar92** [comment]
Hmm. I do not use org-noter, so it is hard for me to test. However, I can see that it uses some functions from outline-mode in the code. Can you try to change `outline-show-entry` to `org-show-entry` and  `outline-hide-subtree` to `org-fold-hide-subtree` in the org-noter code on your side?

**Comment by tpeacock19** [comment]
I experienced a similar issue with [org-fc](https://git.sr.ht/~l3kn/org-fc) and it was solved by changing those functions you mentioned. Aside from changing the code locally, is there any other approach we could take to solve this? Perhaps advising outline functions in the meantime?

**Comment by yantar92** [comment]
> Aside from changing the code locally, is there any other approach we could take to solve this? Perhaps advising outline functions in the meantime?

You can use the following advises:

(define-advice outline-show-entry (:around (oldfun) fix-for-org-fold)
  "Run `org-fold-show-entry' version of the function when in org-mode."
  (if (eq major-mode 'org-mode)
      (org-fold-show-entry)
    (funcall oldfun)))

(define-advice outline-hide-subtree (:around (oldfun) fix-for-org-fold)
  "Run `org-fold-show-entry' version of the function when in org-mode."
  (if (eq major-mode 'org-mode)
      (org-fold-hide-subtree)
    (funcall oldfun)))

I think I can add these two and similar advises for other
folding-related outline functions right in this branch. I suspect that
many packages may be using functions from outline-mode assuming that
they also work in org-mode (which is mostly correct for current master,
but not for this branch).

**Comment by yantar92** [comment]
@tpeacock19,@Ypot Can you test if your issue is solved now (even without advices in your config)?

**Comment by tpeacock19** [comment]
I can confirm that org-fc works without the advices on the latest commit.

**Comment by tpeacock19** [comment]
It did, however, introduce another issue. `org-fold-hide-subtree` does not cleanly fold headings. For example in the below pictures I executed `(org-fold-hide-subtree 1)` as this is essentially what `evil-close-folds` is in org-mode. It results in an extra ellipsis. 

![2021-01-27T15:33:26_screenshot](https://user-images.githubusercontent.com/6407145/106065342-6a622d00-60b8-11eb-9f94-a29708da0a94.png)


![2021-01-27T15:33:31_screenshot](https://user-images.githubusercontent.com/6407145/106065351-6f26e100-60b8-11eb-9ec0-00f8c5bc7b54.png)

I have identified a solution by changing the below function.

```diff
diff --git a/lisp/org-fold.el b/lisp/org-fold.el
index 55dea6fdb..545d62437 100644
--- a/lisp/org-fold.el
+++ b/lisp/org-fold.el
@@ -788,8 +788,7 @@ of the current heading, or to 1 if the current line is not a heading."
       (org-map-region
        (lambda ()
 	 (when (<= (funcall outline-level) levels)
-	   (org-fold-show-entry)
-           (org-fold-hide-entry)))
+           (org-fold-heading nil)))
        beg end)
       ;; Finally unhide any trailing newline.
       (goto-char (point-max))

```

**Comment by yantar92** [comment]
I can confirm the issue. Though the proposed solution is not fixing the origin of the problem (which should be in the recent changes). So, let me debug further to find the actual cause.

**Comment by yantar92** [comment]
The bug existed in `org-fold-hide-sublevels` from the time I wrote it (this is a new function introduced in this branch). Now, it revealed itself because `outline-hide-sublevels` is adviced to use the org version. @tpeacock19 You suggestion should be the right fix. Thanks!

**Comment by tpeacock19** [comment]
great. I'll keep looking to see if there are any other downstream effects from the changes.
