### ISSUE TITLE
org-version not set

### ISSUE THREAD

**Issue by novoid** [yantar92/org#2]
Hi, 
Emacs 26.1 and 26.3, latest commit from this repo (faf9039c7).

`M-x org-version` is not set which is causing misc side-effects.

-------------

I've got an issue with `M-x yankpad-expand` yankpad (yasnippet-extension) which results in the inability to use my snippets. The error is: `version-to-list: Invalid version syntax: ‘’ (must start with a number)` which I guess could be related to the missing org version.

**Comment by yantar92** [comment]
Did you run `make autoloads` in the cloned repo?

**Comment by novoid** [comment]
I did `make all`.
As I could not find out in the Makefile if `make all` also contains the target `autoloads` I did a `make autoloads` and still do not have an org version in my Emacs (after restarting).

**Comment by yantar92** [comment]
I confirm that `make autoloads` does not work if I download repo from github. Let me investigate.

**Comment by yantar92** [comment]
I found what was the problem. I did not push tags to github repo. The last release tag info is required to generate org-version string. `make autoloads` should work fine if you clone the repo again.

**Comment by novoid** [comment]
I can confirm that org-version now works. 

My yankpad issue persists, so it is independent of org-version.

**Comment by yantar92** [comment]
> My yankpad issue persists, so it is independent of org-version. 

I just tried to install yankpad and I cannot reproduce the issue on my
side. It would be helpful if you can construct minimal config and steps
to reproduce the issue.

**Comment by novoid** [comment]
Oh, this is very nice of you - I was not implying you to install yankpad and trying to reproduce the issue.

Don't worry - most likely the creation of a minimal example would take me at least a day and I probably would be able to fix it then myself. Because of the complexity to come up with a minimal example, I won't invest time into that task.
