### ISSUE TITLE
org-show-entry fails on heading beginning at point 1

### ISSUE THREAD

**Issue by AloisJanicek** [yantar92/org#20]
**Describe the bug**
`org-show-entry` errors out with `args-out-of-range 0 13` when executed on heading which begins at point `1` (is the first thing in the org file)

**Expected behavior**
`org-show-entry` will unfold/show the entry regardless of where in the file it begins

**To Reproduce**
Create new org document with following content:
```
* Test heading
  asdf
```
move point over the heading and execute `org-show-entry`

there should be `args-out-of-range 0 13` error in the echo messages area.

**Example debug output**
<details><summary>example debug output</summary>
<p>

````

Debugger entered--Lisp error: (args-out-of-range 0 241)
  org-fold-region(0 241 nil headline)
  outline-flag-region@fix-for-org-fold(#<subr outline-flag-region> 0 241 nil)
  apply(outline-flag-region@fix-for-org-fold #<subr outline-flag-region> (0 241 nil))
  outline-flag-region(0 241 nil)
  outline-show-entry()
  [...]
````

</p>
</details>

**Further information**
I think the issue comes from:
```
 (outline-flag-region (1- (point))
```
in [emacs/lisp/outline.el/outline-show-entry](https://github.com/emacs-mirror/emacs/blob/master/lisp/outline.el#L863)

which due to advice calls `org-fold-region` on region beginning at `0`.

**Comment by yantar92** [comment]
I cannot reproduce.

>  (outline-flag-region (1- (point))

This means that you are actually not using org-fold branch. All the calls
to `outline-flag-region` are eliminated here.

You can refer to https://github.com/yantar92/org#installation for
installation instructions and to
https://github.com/yantar92/org#testing-the-branch to make sure that
nothing in your config is causing other version of org-mode to load.

**Comment by AloisJanicek** [comment]
I've added example debug output to my OP, there is `outline-flag-region@fix-for-org-fold` in there
