### ISSUE TITLE
org-save-outline-visibility macro throws `void-variable type` error

### ISSUE THREAD

**Issue by telotortium** [yantar92/org#21]
**Describe the bug**

A variable `type` is referenced in the macro as a free variable. Found in commit a07dfb511 here: https://github.com/yantar92/org/blob/a07dfb5116936eeb822d86caf9314153462da163/lisp/org-fold.el#L329

**Expected behavior**

This error shouldn't be thrown. I think you meant to write `spec` here.

**To Reproduce**

I think any call to `org-save-outline-visibility` will cause this. I encountered this from `org-drill`: https://gitlab.com/phillord/org-drill/-/blob/35c1ce349949cc213f3076799211210f49431850/org-drill.el#L2406.

**Comment by yantar92** [comment]
Already fixed in a40d4153. I was just about to push it ;)
