### ISSUE TITLE
Table alignment is off when using org-indent-mode

### ISSUE THREAD

**Issue by andersjohansson** [yantar92/org#25]
**Describe the bug**
When using org-indent-mode, table alignment doesn’t seem to work correctly. In a table with only text and no links or anything hidden, the fields are not getting aligned correctly trying to align some fields results in errors.

**Expected behavior**
Correct alignment

**To Reproduce**
With clean configuration:
1. Create org buffer
2. Insert example table:
```
| test first line  | second column |
| test second line |               |
```
3. Activate `org-indent-mode`
4. Place cursor in second line and press `<tab>`. This results in an error in `org-table--align-field`, because `org-string-width` returns the width of the field as `18` (it is 16 characters), so `spaces` becomes negative. 

The logic introduced in `org-string-width` in commit fca3c0730 doesn’t seem to take care of this case so well. I don’t quite understand what it is supposed to do, but it seems a bit tricky to measure pixel width in a temporary buffer in that way. I’ve struggled a bit with that and found for example that face-remappings (text-scale, variable-pitch) may need to be preserved.
I adapted your code for aligning tags (https://orgmode.org/list/87lfh745ch.fsf@localhost/) because of this:
```
(defun aj/string-pixel-width (string &optional mode)
  "Calculate pixel width of STRING.
Optional MODE specifies major mode used for display."
  (let ((fra face-remapping-alist))
    (with-temp-buffer
      (with-silent-modifications
        (setf (buffer-string) string))
      (when (fboundp mode)
        (funcall mode)
        (font-lock-ensure))
      (setq-local face-remapping-alist fra)
      (if (get-buffer-window (current-buffer))
	      (car (window-text-pixel-size nil (line-beginning-position) (point)))
        (set-window-buffer nil (current-buffer))
        (car (window-text-pixel-size nil (line-beginning-position) (point)))))))
```

**Comment by andersjohansson** [comment]
That was quick! Seems to solve the immediate issue with `org-indent-mode`. Thanks!

**Comment by yantar92** [comment]
I could not quite reproduce the error you described, but the return
value of 18 instead of 16 characters in your example is indeed
incorrect. The problem with return value is fixed now and hopefully also
fixes the bug on your side.

> I’ve struggled a bit with that and found for example that
> face-remappings (text-scale, variable-pitch) may need to be preserved.

Text-scale and variable-pitch should not affect org-string-width -- it
supposed to return width in number of symbols. There is no support for
variable-pitch in org-table for now.

> I adapted your code for aligning tags ***@***.***/) because of this:

Interesting. Thanks for sharing. It may explain why some tags are not
aligned in my personal Emacs config.

**Comment by andersjohansson** [comment]
> I could not quite reproduce the error you described, but the return value of 18 instead of 16 characters in your example is indeed incorrect. The problem with return value is fixed now and hopefully also fixes the bug on your side.

Yes, it seems to work for me, even if I've not done extensive tests.

> Text-scale and variable-pitch should not affect org-string-width -- it supposed to return width in number of symbols. There is no support for variable-pitch in org-table for now.

Seems reasonable, even though I use variable-pitch for org-mode, the `org-table` face inherits `fixed-pitch`, so all works fine. And text-scale doesn't matter either of course when it is calculating the width in number of symbols in a fixed-pitch face.

> I adapted your code for aligning tags because of this:
> Interesting. Thanks for sharing. It may explain why some tags are not aligned in my personal Emacs config.

:+1:

**Comment by tpeacock19** [comment]
I'm still running into issues with org-tables. however, I do not have `org-indent-mode` activated. The below table is after using `org-table-align`

```
| one | two  | three  |   | random |
|---+----+----+---+---|
| a | another | note  | notes |   |
|   |    | something |   |   |
```

I'm using a `fixed-pitch`. I think there is an inconsistency with what I'm seeing below. I imagine given your `org-string-width` function you would see different values for the below?

``` elisp
;; buffer with only the word "four"
(with-current-buffer "*new*"
  (window-text-pixel-size
   nil (line-beginning-position) (point-max)))
;; => (90 . 21)
(with-current-buffer "*new*<2>"
  (window-text-pixel-size
   nil (line-beginning-position) (point-max)))
;; => (60 . 21)
```

**Comment by yantar92** [comment]
> I'm still running into issues with org-tables. however, I do not have `org-indent-mode` activated. The below table is after using `org-table-align`

I cannot reproduce. The table is aligned correctly on my side. Did you check with clean Emacs?

**Comment by tpeacock19** [comment]
I figured out it has to do with the `display-line-numbers` setting I have in my config. I think it interferes with the alignment if it is set to anything aside from `nil`. Most likely having to do with the temp buffer in `org-string-width`. I was able to do the below for a quick fix:

```diff
diff --git a/lisp/org-macs.el b/lisp/org-macs.el
index 292ef8019..cbd27affb 100644
--- a/lisp/org-macs.el
+++ b/lisp/org-macs.el
@@ -900,6 +900,7 @@ Return width in pixels when PIXELS is non-nil."
                result)))
         (current-char-property-alias-alist char-property-alias-alist))
     (with-temp-buffer
+      (setq-local display-line-numbers nil)
       (setq-local buffer-invisibility-spec
                   current-invisibility-spec)
       (setq-local char-property-alias-alist
```

**Comment by yantar92** [comment]
> ... I was able to do the below for a quick fix:

Thanks! Applied.
