### ISSUE TITLE
When `org-clock-in`, `ad-Advice-outline-back-to-heading: peculiar error` was raised

### ISSUE THREAD

**Issue by dsdshcym** [yantar92/org#29]
**Describe the bug**
When `org-clock-in`, `ad-Advice-outline-back-to-heading: peculiar error` was raised

**Expected behavior**
Clock starts as normal

**To Reproduce**
Let me know if you cannot reproduce this issue, I will try to reproduce it in vanilla emacs.

---
After commenting out this line: https://github.com/yantar92/org/blob/ba5ad1221e68cb0de67b51cde5de46cfd39e230b/lisp/org-compat.el#L1319, I can clock-in as normal

**Comment by yantar92** [comment]
> When `org-clock-in`, `ad-Advice-outline-back-to-heading: peculiar error` was raised

This implies that point position somehow goes before the first heading.
The problem should not be with outline-back-to-heading, but with
something else.

> Let me know if you cannot reproduce this issue, I will try to reproduce it
> in vanilla emacs.

I use `org-clock-in` all the time and do not see any issue. Reproducer
would be helpful.

**Comment by dsdshcym** [comment]
Okay, after some debugging, I think I've found the cause:

I can reproduce this issue in a org file whose first line is not a heading
[reproduce.org.txt](https://github.com/yantar92/org/files/6411316/reproduce.org.txt)

If the first line is a heading, then I can clock-in just fine:
[normal.org.txt](https://github.com/yantar92/org/files/6411318/normal.org.txt)

**Comment by yantar92** [comment]
> I can reproduce this issue in a org file whose first line is not a heading
> [reproduce.org.txt](https://github.com/yantar92/org/files/6411316/reproduce.org.txt)

I just tried your file. I still cannot reproduce. Can you try running
emacs from inside the org-mode folder like `emacs -Q -L ./lisp -l org`?

**Comment by dsdshcym** [comment]
@yantar92 yes, I can still reproduce this issue with `emacs -Q`

BTW, I'm using emacs 27.2, not sure if you are using emacs master or not.


EDIT:
I just confirmed, with `emacs-28.0.50 -Q`, I can clock-in inside reproduce.org.txt

**Comment by yantar92** [comment]
> BTW, I'm using emacs 27.2, not sure if you are using emacs master or not.

Thanks! I was finally able to reproduce the issue using Emacs 27. It did
not show up on Emacs master, which I am using.

**Comment by dsdshcym** [comment]
Thanks for the quick response and fix!

**Comment by yantar92** [comment]
Happy May day ;)
