### ISSUE TITLE
not actually performing the fold for me

### ISSUE THREAD

**Issue by titaniumbones** [yantar92/org#3]
Hi, I'm excited to try out this branch! Unfortunately when I load it org-cycle no longer appears to cycle visibility of headlines.

Emacs-version: recent git of the native-comp pgtk branch: 

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3) of 2020-11-2

To reproduce

Open test org file, e.g. 

```
* heading
text
```
navigate to heading and press tab or `M-x org-cycle`.

New org-cycle state will display in `*Messages*` but visible text will not change.  

can you help me debug/would you prefer that I post messages to org-mode list?

**Comment by yantar92** [comment]
I cannot reproduce on my side with native-comp GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, cairo version 1.16.0) of 2020-12-09

Can you reproduce with emacs -Q (https://github.com/yantar92/org#testing-the-branch)?

**Comment by titaniumbones** [comment]
hmm. reinstalled emacs and then ran the emacs -Q command din #testing-the-branch (which I missed at first, sorry) -- can no longer reproduce the error, so I'll close this issue. Sorry for the hassle!
