### ISSUE TITLE
Links are not fontified in *Clock Task Select* buffer

### ISSUE THREAD

**Issue by dsdshcym** [yantar92/org#30]
**Describe the bug**
When calling `(org-clock-goto t)`, it would open a buffer `*Clock Task Select*` and list all the recent clocked-in tasks' headers for selection
With `feature/org-fold-universal-core` branch, links in the headers are not fontified:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/4723751/116815006-15b4cf00-ab4b-11eb-8f91-609dbd9f7443.png">

**Expected behavior**
Links in `*Clock Task Select*` buffer are fontified as in org buffers:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/4723751/116815042-4432aa00-ab4b-11eb-9da7-89a2f723afb6.png">
^ this screenshot was taken after `(setq org-fold-core-style 'overlays)`

**To Reproduce**
1. create a heading which has a link (`[[https://google.com][test]]`) in header
2. org-clock-in
3. eval `(org-clock-goto t)`

**Comment by yantar92** [comment]
> When calling `(org-clock-goto t)`, it would open a buffer `*Clock Task Select*` and list all the recent clocked-in tasks' headers for selection
> With `feature/org-fold-universal-core` branch, links in the headers are not fontified:

Confirmed and fixed. Thanks for reporting! It is one of the use-cases I almost
forgot about.
