### ISSUE TITLE
Cache warnings

### ISSUE THREAD

**Issue by andersjohansson** [yantar92/org#35]
**Describe the bug**
I get warnings about "Got element without parent." This is with org from the latest commit ec3603 (but I also have some (I hope) quite unrelated patches in other parts of org).

**Expected behavior**
No warnings.

**To Reproduce**
I have not had the time to pinpoint exactly why this happens and if it may be due to my config yet, but wanted to give a heads up that it occurs for me.

Last time, it was when I had a tree like this:
```org-mode
* First
**  Second
**  Third
```
and removed the extra (doubled) space in the beginning of Second and Third. Both these actions gave the warning for these headlines as the elements without parent.

**Comment by yantar92** [comment]
Can you try with the latest master? It should fix at least some of the cache issues.

If you keep seeing warnings, can you also try to reproduce with `org-element--cache-self-verify` set to `backtrace`? The warning will then be supplied with backtrace that can hopefully reveal what is going on.

**Comment by andersjohansson** [comment]
Thank you! Trying it out now. Haven't seen any warnings yet so I'll keep cache on and see if anything appears over the next days.

**Comment by andersjohansson** [comment]
I am not getting the same warnings anymore, but cannot display my agenda at all.

When calling org-agenda I get these warnings repeatedly, for several of my agenda files:
```
Warning (emacs): org-element--cache: Cache corruption detected in G.org. Resetting.
 The error was: (error "Variable binding depth exceeds max-specpdl-size") Disable showing Disable logging
Warning (emacs): org-element--cache: Cache corruption detected in G.org. Resetting.
 The error was: (error "Variable binding depth exceeds max-specpdl-size") Disable showing Disable logging
...
```
And emacs locks up. For some reason resetting the cache doesn't seem to work. 

```
max-specpdl-size is a variable defined in ‘C source code’.

Its value is 2946
Original value was 2500
```
Tried increasing `max-specpdl-size` to 20000 but then got a similar lockup, with this warning instead:
```
Warning (emacs): org-element--cache: Cache corruption detected in G.org. Resetting.
 The error was: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’") Disable showing Disable logging
```

I haven’t been able to produce a minimal example to reproduce this, but perhaps this can give some ideas for you? I can try any other ways of debugging you recommend . It doesn't seem to be just a specific file or incorrect org syntax in a specific file (but the char positions reported by the backtrace below seems to be at the beginning of line for my category preamble lines: `#+CATEGORY: jp`)

Below is a backtrace obtained when stopping emacs with `kill -SIGUSR2` during this:

```
Debugger entered--entering a function:
* #f(compiled-function () #<bytecode -0x1e3deafb9c13b78>)()
  debug(lambda)
* undo-tree-post-gc()
  #f(compiled-function () #<bytecode -0x1e3de08181daf78>)()
  debug(lambda)
* #f(compiled-function () #<bytecode -0x4934077a32423ed>)()
  org-element--parse-to(109)
  org-element-at-point(nil cached-only)
  org-element-at-point-no-context()
  org-element-org-data-parser()

[... These 4 lines repeated 200 times ...]
  org-element--parse-to(109)
  org-element-at-point(nil cached-only)
  org-element-at-point-no-context()
  org-element-org-data-parser()

  org-element--parse-to(109)
  org-element-at-point(nil cached-only)
  org-element-at-point-no-context()
  org-element-org-data-parser()
  org-element--parse-to(470)
  org-element-at-point()
  org-fold--hide-drawers--text-properties(1 1325)
  org-fold--hide-drawers(1 1325)
  org-cycle-hide-drawers(all)
  org-cycle-set-startup-visibility()
  org-mode()
  set-auto-mode-0(org-mode nil)
  set-auto-mode--apply-alist((( ....) nil nil)
  #<subr set-auto-mode>()
  so-long--set-auto-mode(#<subr set-auto-mode>)
  apply(so-long--set-auto-mode #<subr set-auto-mode> nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer G.org> "~/org/imp/G.org" nil nil "~/org/imp/G.org" (28704971 65026))
  find-file-noselect("/home/aj/org/imp/G.org")
  org-get-agenda-file-buffer("/home/aj/org/imp/G.org")
  org-agenda-prepare-buffers((REDACTED LIST OF FILENAMES))
  org-agenda-prepare("Day/Week")
  #f(compiled-function (&optional arg start-day span with-hour) "Produce a daily/weekly view from all files in variable `org-agenda-files'.\nThe view will be for the current day or week, but from the overview buffer\nyou will be able to go to other days/weeks.\n\nWith a numeric prefix argument in an interactive call, the agenda will\nspan ARG days.  Lisp programs should instead specify SPAN to change\nthe number of days.  SPAN defaults to `org-agenda-span'.\n\nSTART-DAY defaults to TODAY, or to the most recent match for the weekday\ngiven in `org-agenda-start-on-weekday'.\n\nWhen WITH-HOUR is non-nil, only include scheduled and deadline\nitems if they have an hour specification like [h]h:mm." (interactive "P") #<bytecode -0xae0e9dc60cea160>)(nil)
  apply(#f(compiled-function (&optional arg start-day span with-hour) "Produce a daily/weekly view from all files in variable `org-agenda-files'.\nThe view will be for the current day or week, but from the overview buffer\nyou will be able to go to other days/weeks.\n\nWith a numeric prefix argument in an interactive call, the agenda will\nspan ARG days.  Lisp programs should instead specify SPAN to change\nthe number of days.  SPAN defaults to `org-agenda-span'.\n\nSTART-DAY defaults to TODAY, or to the most recent match for the weekday\ngiven in `org-agenda-start-on-weekday'.\n\nWhen WITH-HOUR is non-nil, only include scheduled and deadline\nitems if they have an hour specification like [h]h:mm." (interactive "P") #<bytecode -0xae0e9dc60cea160>) nil)
  org-agenda-list(nil)
  funcall-interactively(org-agenda-list nil)
  call-interactively(org-agenda-list)
  org-agenda(nil)
  funcall-interactively(org-agenda nil)
  command-execute(org-agenda)
```

**Comment by yantar92** [comment]
>   org-element--parse-to(109)
>   org-element-at-point(nil cached-only)
>   org-element-at-point-no-context()
>   org-element-org-data-parser()

Seems to be interaction between
org-element--cache-non-modifying-commands and
org-element-org-data-parser. Should be fixed with the latest commit if I
understood the backtrace correctly.

**Comment by andersjohansson** [comment]
Tested out the newest commits (d9b8a7) but encountered the same problem. But it seems it is due to incorrect (or incorrectly parsed) org syntax in my files after all.

Some of my agenda files were converted from ical with a script and got an empty EMAIL-property set. A minimal example below. The point where it all locks up is on char 11, that is on the `#` on line 2. I'll start by fixing my files. Even if this is formally wrong org syntax, that emacs locks up is of course not so user friendly 🙂. I hope this helps!

```org-mode
#+EMAIL: 
#+CATEGORY: category

* TODO A task
SCHEDULED: <2021-09-23 tor>
```

**Comment by andersjohansson** [comment]
No, it doesn't seem to be only this. Another thing I have in my agenda-files is categories for subtrees, using "icons" by way of emoji unicode characters.

When setting `org-agenda-files` to a list of only the file below.


This locks up with `org-element--parse-to(1)`: 

```
#+CATEGORY: jp
#+STARTUP: content

* With bad category
:PROPERTIES:
:CATEGORY: 📥
:END:

```

But this works and displays an empty agenda:
```
#+CATEGORY: jp
#+STARTUP: content

* Without bad category
```

**Comment by yantar92** [comment]
Anders Johansson ***@***.***> writes:

> Tested out the newest commits (d9b8a7) but encountered the same problem. But it seems it is due to incorrect (or incorrectly parsed) org syntax in my files after all.

Are you seeing exactly same backtrace? If the backtrace is same, there
should be some issue with macro call. I tried another variant without
macro in c49ed3f. Not sure if it can help though.

> Some of my agenda files were converted from ical with a script and got an empty EMAIL-property set. A minimal example below. The point where it all locks up is on char 11, that is on the `#` on line 2. I'll start by fixing my files. Even if this is formally wrong org syntax, that emacs locks up is of course not so user friendly 🙂. I hope this helps!
>
> ```org-mode
> #+EMAIL: 
> #+CATEGORY: category
>
> * TODO A task
> SCHEDULED: <2021-09-23 tor>
> ```

Unfortunately, I cannot reproduce. This file have perfectly fine syntax.
Empty keyword fields are allowed.

If would be helpful if you provided backtrace.

**Comment by yantar92** [comment]
> Unfortunately, I cannot reproduce. This file have perfectly fine syntax.
> Empty keyword fields are allowed.

Ok. I managed to reproduce the infinite recursion. Disabling cache did
not work reliably because it tried to override a defsubst. Apparently,
such override did not work reliably depending if the function is
byte-compiled or not.

**Comment by andersjohansson** [comment]
Ah, great! It seems to work well now. Great that my confused testing got you on the right track! Closing this now and I'll open another issue if I bump into other problems.
