### ISSUE TITLE
`file-name-concat` function isn't available for many users

### ISSUE THREAD

**Issue by AloisJanicek** [yantar92/org#36]
`file-name-concat` used a lot in [org-element.el](https://raw.githubusercontent.com/yantar92/org/feature/org-fold-universal-core/lisp/org-element.el) is just [2 months old](https://github.com/ayatakesi/emacs-mirror/commit/f04f8126f016b43c45d432bf353ba2a0ac8f7d96) function name from emacs' `master`, users wishing to test `org-fold` will inevitably run into issues unless they use recent emacs from the `master` branch. Users should be at least informed in README about this but more preferably there should be some conditionals or hacks deployed on `org-fold`'s side instead.

**Comment by AloisJanicek** [comment]
~~Also this is pretty brutal thing to do on emacs' side, I am on \~2 weeks old commit from `master` and there is no obsolete alias to `directory-append`.~~

edit: Oh, I see, `directory-append` was just new function from [1 day earlier.](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=5431a58e86d3f2579c1edf1dc8d7074de73ac694), that clears things up a little.

**Comment by yantar92** [comment]
Thanks for the heads up!

I am developing this on latest Emacs, though the final intention is full
support of all Emacs versions that Org supports. So, compatibility
issues slip through the cracks from time to time.
