### ISSUE TITLE
Error during redisplay: Jit lock function and compiler error 

### ISSUE THREAD

**Issue by SterlingHooten** [yantar92/org#43]
Org mode isn't loading the overlays, and is instead giving a
`Error during redisplay: (jit-lock-function 1) signaled (wrong-number-of-arguments #<subr null> 2)`
During the make process it gave error:
```
org-font-lock-core.el:176:18:Warning: ‘not’ called with 2 args, but requires 1
org-font-lock-core.el:176:23:Warning: ‘eq’ called with 1 arg, but requires 2
org-font-lock-core.el:176:23:Warning: eq called with 1 argument, but requires 2
org-font-lock-core.el:176:23:Warning: ‘not’ called with 2 args, but requires 1
org-font-lock-core.el:176:23:Warning: ‘eq’ called with 1 arg, but requires 2
org-font-lock-core.el:176:23:Warning: eq called with 1 argument, but requires 2
```

**Expected behavior**
This is my first time running this distribution, was expecting something like stock org to load with a simple file. 

**To Reproduce**
Pulled most recent from main in shell
Make in shell
emacs -Q
(add-to-list 'load-path "~/code/emacs/org/lisp/")
(require 'org-loaddefs)
Open a simple test.org file

**Comment by yantar92** [comment]
Note that folding without overlays is now merged upstream. You can simply use main branch from Org repo (https://git.savannah.gnu.org/cgit/emacs/org-mode.git) or install Org from ELPA devel (https://protesilaos.com/codelog/2022-05-13-emacs-elpa-devel/). 

I am currently using this repo for development of more accurate fontification (https://orgmode.org/list/87ee7c9quk.fsf@localhost). The current implementation requires Emacs 28 or newer and you are using an older Emacs version.

If your intention is to test the new fontification engine, I can quickly fix the issue right now.
