### ISSUE TITLE
org-toggle-link-display doesn't work

### ISSUE THREAD

**Issue by andersjohansson** [yantar92/org#7]
**Describe the bug**
In the current code, `org-toggle-link-display` doesn't seem to work.

**Expected behavior**
`org-toggle-link-display` should alternatively show and hide full links.

**To Reproduce**
Open an org file with links. Invoke `org-toggle-link-display`. No change is seen. 

** Debugging
Stepping through `org-toggle-link-display` with edebug, the hiding and showing seems to work at first but the effect is reverted by `org-restart-font-lock`. I haven’t been able to figure out why though.

So actually, this seems to work as expected, but maybe that misses something important?
````emacs-lisp
(defun org-toggle-link-display ()
  "Toggle the literal or descriptive display of links in current buffer."
  (interactive)
  (if org-link-descriptive (org-fold-remove-folding-spec 'org-link)
    (org-fold-add-folding-spec 'org-link nil 'hide-completely 'no-isearch-open 'append))
  ;; (org-restart-font-lock)
  (setq org-link-descriptive (not org-link-descriptive)))
````

**Comment by yantar92** [comment]
Thanks for reporting. I accidently introduced this in another fix to link fontification in org-agenda.
