### ISSUE TITLE
Change in colors

### ISSUE THREAD

**Issue by Ypot** [yantar92/org#8]
**Describe the bug**
There is a change in the color of the states. They seem to take the color of the level where they are.

**Expected behavior**
Maintain default color.

New behaviour:
![1](https://user-images.githubusercontent.com/30699014/102754558-764a2900-436d-11eb-9857-2f52bea742eb.JPG)

Expected behaviour:
![2](https://user-images.githubusercontent.com/30699014/102754575-7a764680-436d-11eb-96b7-1061ad2e910b.JPG)

**Comment by yantar92** [comment]
Could you run `M-x describe-text-properties` in these two cases and post the result? Also, there have been changes to headline face calculation in 979e82fc3 a few months ago. What was the Org version you were using before trying this branch?

**Comment by Ypot** [comment]
After updating ORG:

![2](https://user-images.githubusercontent.com/30699014/102776873-cb973200-438f-11eb-8511-e8f9bb88a2d7.JPG)

```
Text content at position 22721:
There are text properties here:
  face                 (:background "chocolate" :height 0.75 :box (:line-width 2 :style released-button))
  fontified            t
  line-prefix          [Show]
  wrap-prefix          [Show]

```


![1](https://user-images.githubusercontent.com/30699014/102776247-b241b600-438e-11eb-9321-2d9f2d8f7d21.JPG)
```
Text content at position 22721:
There are text properties here:
  face                 ((:background "chocolate" :height 0.75 :box (:line-width 2 :style released-button)) org-level-2)
  fontified            t
  isearch-open-invisible org-fold--isearch-show
  isearch-open-invisible-temporary org-fold--isearch-show-temporary
```

**Comment by yantar92** [comment]
> After updating ORG:

Can you confirm that your `M-x org-version` is above 9.4 for the first screenshot? Starting from Org 9.4.1 all the elements of headline inherit the headline face - it is what you see on second screenshot and in `'face` property containing `org-level-2` face.

**Comment by Ypot** [comment]
> 
> 
> > After updating ORG:
> 
> Can you confirm that your `M-x org-version` is above 9.4 for the first screenshot? Starting from Org 9.4.1 all the elements of headline inherit the headline face - it is what you see on second screenshot and in `'face` property containing `org-level-2` face.


`
Org mode version 9.4.3 (9.4.3-1-g6ec2bb-elpa @ ~/.emacs.d/elpa/org-20201221/)`

**Comment by yantar92** [comment]
I think I understand what happenned. ELPA uses maint branch, while the headline face inheritance is now on master branch. What you are seeing has nothing to do with this org-fold branch, but rather a side-effect that this branch is built on top of the latest available version of org (which is master branch). The behavior you observe will be introduced into Org 9.5 release in future. See https://protesilaos.com/codelog/2020-09-24-org-headings-adapt/ for details why. 

In your case, you need to change you todo keyword face customisation to something like `  (setq org-todo-keyword-faces '(("TODO" :inherit default :background "chocolate" :height 0.75 :box (:line-width 2 :style released-button))))` - you need to state explicitly that you want to inherit default face.
